APP_NAME = "TODO API"
WEB_PORT = ":5000"

[DATABASE]
DRIVER_NAME = "mysql"
CONNECTION_SOURCE = "root:root@tcp(localhost:3306)/db_todo?parseTime=true"

[CACHE]
DRIVER_NAME = "redis"

    [CACHE.REDIS]
    HOST = "localhost"
    PORT = 6379
    DB = 0
    PASS = ""
    PREFIX = "dev"

[BCRYPT]
ROUND = 12

[JWT]
ALGORITHM = "HS256"
KEY_SECRET = "Secr3t"
DURATION = 60000 # seconds

[MIGRATE]
DRIVER_NAME = "native"
PATH_MIGRATIONS = "./scripts/migrations"
# PATH_MIGRATIONS = "./../../scripts/migrations"
